

---
title: "extratos"
output:
  output_dir: docs
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: https://github.com/andreferraribr
    social: [ "twitter", "facebook", "menu" ]
    
runtime: shiny    

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=999)
```




```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(rjson)
library(stringr)
library(jsonlite)
library(httr)
library(purrr)
library(readxl)
library(DT)
library(plotly)
library(shiny)
library(shinyWidgets)
library(flexdashboard)
library(ggplot2)
library(stringr)
library(plotly)
library(knitr)
library(shiny)
library(lubridate)
library(tidyverse)
# library(janitor)
```
        






```{r include=FALSE}
# 
# Criei a função json2df(). A função baixa o arquivo JSON e armazenar os dados em uma data frame.
# 
# A função foi inspirada no código do Marcos F Silva https://www.rpubs.com/marcosfs2006/api_siconfi.

json2df = function(a){ 

# "a" é a URL
f_api <-   GET(a)

f_txt <- content(f_api, as="text", encoding="UTF-8")

f_json <- fromJSON(f_txt, flatten = FALSE)

f_df <-as.data.frame(f_json[[1]]) 

}
```





```{r include=FALSE}
# função para juntar data frames

bind_json2df = function(a){ map(a,json2df)}
```



```{r include=FALSE}

# A função relatorios() acessa as urls, baixa os arquivos JSON, transforma os arquivos individuais em data frames, agrupa as data frames em uma única data frame. 

# funcao para gerar df com os dados dos relatórios
relatorios = function(a){map_dfr(bind_json2df(a), bind_rows)}

```
  
   






```{r include=FALSE}
# acessar url com dados dos entes

# Utilizei a função json2df para criar uma data frame com os dados dos entes da federação.
# entes<- json2df("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/entes")

entes <- read_csv("entes.csv") %>%  mutate(esfera_nome =  case_when(
  esfera == "M" ~ paste0("município de ",ente,"-",uf),
  esfera == "E"  | ente  %in% c("Rio de Janeiro","São Paulo") ~ paste0(ente," (Estado)"),
  TRUE ~ ente))


periodo <- (2015:as.integer(format(Sys.Date(), "%Y")))


# 
# %>%  mutate(ente_uf =  case_when(
#   esfera == "M" ~ paste0(ente," município ",uf),
#   esfera == "U" ~ paste0(ente,"-","Brasil"),
#   esfera %in% c("E","D") ~ paste0(ente,"-","Estado/DF")))




```



  
```{r include=FALSE}

# periodo <- (2015:as.integer(format(Sys.Date(), "%Y")))

# https://stackoverflow.com/questions/30472625/r-shiny-how-to-get-current-year-with-sys-date
 # sliderInput ("ano", "período", min = 2015, max = max(periodo), value = c(min(periodo), max(periodo)), step = 1)
```



    



```{r}

# apresentar exemplo da estrutura do extrato

cod_ibge <- reactive(entes %>% filter(esfera_nome == input$esfera_nome) )

# DTOutput("ente")
# 
# output$ente <- renderDT({datatable(cod_ibge())})

# output$extratos <- renderDT({datatable(entes %>% filter(esfera_nome == input$esfera_nome))})





# 
# 
# # tornar amigavel a df extratos
# extratos<- extratos()%>%
#   mutate (data = as.Date (data_status))
# # adicionar variável "tipo" (nome reduzido do entregavel) 
# extratos<- extratos%>%
#   mutate (tipo =case_when(
#  entregavel == "Balanço Anual (DCA)" ~ "DCA", 
#  entregavel == "MSC Agregada" ~ "MSCC",
#  entregavel == "MSC Encerramento" ~ "MSCE",
#  entregavel == "Relatório de Gestão Fiscal" ~ "RGF",
#  entregavel == "Relatório de Gestão Fiscal Simplificado" ~ "RGF Simplificado",
#  entregavel == "Relatório Resumido de Execução Orçamentária" ~ "RREO",
#  entregavel == "Relatório Resumido de Execução Orçamentária Simplificado" ~ "RREO Simplificado"
# ))
# # adicionar variável "poder" (L/legislativo, E/executivo, J/Judiciário...)
# extratos<-extratos%>%
#   mutate (poder = case_when(
#     str_detect(instituicao,'Assembleia Legislativa') ~ "L",
#     str_detect(instituicao,'Câmara de Vereadores') ~ "L",
#     str_detect(instituicao,'Senado Federal') ~ "L",
#     str_detect(instituicao,'Câmara dos Deputados') ~ "L",
#     str_detect(instituicao,'Câmara Legislativa') ~ "L",
#     str_detect(instituicao,'Prefeitura Municipal') ~ "E",
#     str_detect(instituicao,'Governo do') ~ "E",
#     str_detect(instituicao,'Governo Federal') ~ "E",
#     str_detect(instituicao,'Tribunal') ~ "J",
#     str_detect(instituicao,'Conselho da Justiça Federal') ~ "J",
#     str_detect(instituicao,'Conselho Nacional de Justiça') ~ "J",
#     str_detect(instituicao,'Ministério Público') ~ "M",
#     str_detect(instituicao,'Defensoria') ~ "D",
#     str_detect(instituicao,'CONSÓRCIO') ~ "C",
#     str_detect(instituicao,'CONSORCIO') ~ "C",
#     str_detect(instituicao,'Consórcio') ~ "C",
#     TRUE ~ "O"
#   ))
# 
# 






```
  


```{r}



extrato <- reactive(extrato <-  json2df( paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=",cod_ibge()$cod_ibge,"&an_referencia=2020" )) %>%
  mutate (tipo =case_when(
 entregavel == "Balanço Anual (DCA)" ~ "DCA",
 entregavel == "MSC Agregada" ~ "MSCC",
 entregavel == "MSC Encerramento" ~ "MSCE",
 entregavel == "Relatório de Gestão Fiscal" ~ "RGF",
 entregavel == "Relatório de Gestão Fiscal Simplificado" ~ "RGF Simplificado",
 entregavel == "Relatório Resumido de Execução Orçamentária" ~ "RREO",
 entregavel == "Relatório Resumido de Execução Orçamentária Simplificado" ~ "RREO Simplificado"))%>%
  mutate (poder = case_when(
    str_detect(instituicao,'Assembleia Legislativa') ~ "L",
    str_detect(instituicao,'Câmara de Vereadores') ~ "L",
    str_detect(instituicao,'Senado Federal') ~ "L",
    str_detect(instituicao,'Câmara dos Deputados') ~ "L",
    str_detect(instituicao,'Câmara Legislativa') ~ "L",
    str_detect(instituicao,'Prefeitura Municipal') ~ "E",
    str_detect(instituicao,'Governo do') ~ "E",
    str_detect(instituicao,'Governo Federal') ~ "E",
    str_detect(instituicao,'Tribunal') ~ "J",
    str_detect(instituicao,'Conselho da Justiça Federal') ~ "J",
    str_detect(instituicao,'Conselho Nacional de Justiça') ~ "J",
    str_detect(instituicao,'Ministério Público') ~ "M",
    str_detect(instituicao,'Defensoria') ~ "D",
    str_detect(instituicao,'CONSÓRCIO') ~ "C",
    str_detect(instituicao,'CONSORCIO') ~ "C",
    str_detect(instituicao,'Consórcio') ~ "C",
    TRUE ~ "O"
  ))
)


extratos <- c()
periodo <- (2015:as.integer(format(Sys.Date(), "%Y")))

# extratos <-  for (i in (periodo))
# 
# {extrato <- json2df( paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=","4205407","&an_referencia=",as.character(i) ))} 
#   
# {extrato <- json2df( paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=",cod_ibge()$cod_ibge,"&an_referencia=",as.character(i) ))}})


  
# DTOutput("extratos")
# 
# output$extratos <- renderDT({datatable(extrato())})
# 
# {extrato <- json2df( paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=","4205407","&an_referencia=",as.character(i) ))} )})
```


Row {data-height=300}
-------------------------------------

### url_api

```{r}

selectInput("esfera_nome", "ente:", choices=entes$esfera_nome, selected = "município de Florianópolis-SC")

url_api <- reactive(extrato()%>%
  filter(tipo != ("MSCC"),tipo != ("MSCE") )%>%
 mutate (url_api =case_when(
 tipo == "DCA" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/dca?an_exercicio=",exercicio,"&id_ente=",cod_ibge), 
 tipo == "MSCA" ~ "MSCA",
 tipo == "MSCE" ~ "MSCE",
 tipo == "RGF" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rgf?an_exercicio=",exercicio,"&in_periodicidade=",periodicidade,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RGF&co_poder=",poder,"&id_ente=",cod_ibge),
 tipo == "RGF Simplificado" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rgf?an_exercicio=",exercicio,"&in_periodicidade=",periodicidade,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RGF%20Simplificado&co_poder=",poder,"&id_ente=",cod_ibge),
 tipo == "RREO" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rreo?an_exercicio=",exercicio,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RREO&id_ente=",cod_ibge),
 tipo == "RREO Simplificado" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rreo?an_exercicio=",exercicio,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RREO%20Simplificado&id_ente=",cod_ibge)
 
) ))  







DTOutput("url_api")

output$url_api <- renderDT({datatable(url_api())})





```



```{r}
# criar df extratos_relatorios (excluir MSCC e MSCE)
extratos_relatorios<-reactive(extratos()%>%
  filter(tipo != ("MSCC"),tipo != ("MSCE") )%>%
 mutate (url_api =case_when(
 tipo == "DCA" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/dca?an_exercicio=",exercicio,"&id_ente=",cod_ibge), 
 tipo == "MSCA" ~ "MSCA",
 tipo == "MSCE" ~ "MSCE",
 tipo == "RGF" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rgf?an_exercicio=",exercicio,"&in_periodicidade=",periodicidade,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RGF&co_poder=",poder,"&id_ente=",cod_ibge),
 tipo == "RGF Simplificado" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rgf?an_exercicio=",exercicio,"&in_periodicidade=",periodicidade,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RGF%20Simplificado&co_poder=",poder,"&id_ente=",cod_ibge),
 tipo == "RREO" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rreo?an_exercicio=",exercicio,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RREO&id_ente=",cod_ibge),
 tipo == "RREO Simplificado" ~ paste0("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/rreo?an_exercicio=",exercicio,"&nr_periodo=",periodo,"&co_tipo_demonstrativo=RREO%20Simplificado&id_ente=",cod_ibge)
 
) ))
```



    


Row {.tabset .tabset-fade}
-------------------------------------
    
### Download

```{r}
# https://shiny.rstudio.com/reference/shiny/0.14/downloadHandler.html


# rgf_url<-extratos()%>%
#   filter(  tipo == "RGF")
#   rgf <- relatorios(url_api()$url_api)
  

# actionButton("go", "Clique para acessar os dados do SICONFI")
# 
#  # downloadLink("downloadData", "Download")
# 
# dados <- eventReactive(input$go,  relatorios(url_api()$url_api))
# 
# 
# DTOutput("dados")
#  
# 
# output$dados <- renderDT({datatable(dados())})



 downloadLink("downloadData", "Espere carregar a tabela e depois inicie o Download")



  output$downloadData <- downloadHandler(
    filename = function() {
      
      
      paste("data-", Sys.Date(), ".csv", sep="")},
    content = function(file) {write_csv(dados_2(), file)}
  )


  # output$downloadData <- downloadHandler(
  #   filename = function() {
  #     paste("data-", Sys.Date(), ".csv", sep="")
  #   },
  #   content = function(file) {
  #     write_csv(dados(), file)
  #   }
  # )
```


```{r}
# downloadLink("downloadData", "Espere carregar a tabela e depois baixe os dados")
# 
# 
# 
#   output$downloadData <- downloadHandler(
#     filename = function() {
#       paste("data-", Sys.Date(), ".csv", sep="")
#     },
#     content = function(file) {
#       write_csv(dados(), file)
#     }
#   )

# 
#  downloadLink("downloadData", "Espere carregar a tabela e depois inicie o Download")
# 
# 
# 
#   output$downloadData <- downloadHandler(
#     filename = function() {
#       paste("data-", Sys.Date(), ".csv", sep="")
#     },
#     content = function(file) {
#       write_csv(dados(), file)
#     }
#   )

# arq<- c()
# 
# 
# lista_extratos <- reactive({
#   
# arq<- c()
# 
# periodo <- (2015:as.integer(format(Sys.Date(), "%Y")))  
# 
# 
# for (i in periodo){
#   
# files_json <- 
#   paste0 ("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=",cod_ibge()$cod_ibge,"&an_referencia=",toString(i))
# arq<- c(arq, files_json)
# }
# 
# arq
# })

# extrato_2 <- reactive({
#   
#   extrato <-  c()
#     
#   for (i in lista_extratos()) {
#     extrato <- json2df(lista_extratos()[i] )
# 
# }})

# textOutput("extrato_2")
# 
# # output$extrato_2 <- renderDT({datatable(extrato_2())})
# # 
# # 
# output$extrato_2 <- renderText({(lista_extratos())})


```



```{r eval=FALSE, include=FALSE}

arq<- c()


lista_extratos <- ({
  
arq<- c()

periodo <- (2015:as.integer(format(Sys.Date(), "%Y")))  


for (i in periodo){
  
files_json <- 
  paste0 ("http://apidatalake.tesouro.gov.br/ords/siconfi/tt/extrato_entregas?id_ente=","12","&an_referencia=",toString(i))
arq<- c(arq, files_json)
}

arq
})

zzz <-  for (i  in lista_extratos){ json2df(lista_extratos[i])}

```

### reactive

```{r}


# 
# DTOutput("dados")
#  
# 
# output$dados <- renderDT({datatable(dados())})


dataTableOutput('filtro')

output$filtro <- renderDataTable(url_api(), server = TRUE)


# verbatimTextOutput('url')
# 
# output$url <- renderPrint({
#     s = x3_rows_selected
#     if (length(s)) {
#       cat('These rows were selected:\n\n')
#       cat(s, sep = ', ')
#     }
# })

```

### url teste 2


```{r}
actionButton("go_2", "Clique para acessar os dados do SICONFI")

 # downloadLink("downloadData", "Download")




dados_2 <- reactive(relatorios(teste_url()$url_api))

# 
# DTOutput("dados_2")
#  
# 
# output$dados_2 <- renderDT({datatable(teste_url())})

```



### url

```{r}
# verbatimTextOutput('url')
# 
# output$url <- renderPrint({
#     s = input$filtro_rows_selected
#     if (length(s)) {
#       cat('These rows were selected:\n\n')
#       cat(s, sep = ', ')
#     }
# })




DTOutput("dados_2")
 

output$dados_2 <-  renderDT({
                              s = input$filtro_rows_selected
                              if (length(s)) {
                              datatable(dados_2())}})

```

### url teste

```{r}

#  https://yihui.shinyapps.io/DT-rows/

dataTableOutput('url_teste')

output$url_teste <- renderDataTable(url_api() %>% select(url_api) %>% slice (input$filtro_rows_selected) , server = TRUE)

teste_url <- reactive (url_api() %>% select(url_api) %>% slice (input$filtro_rows_selected))

```


